### ISSUE TITLE
perldoc.jpの和訳のチュートリアル記事を書く

### ISSUE THREAD

**Issue by kfly8** [perldoc-jp/wg-perl-document#1]
# 概要

現状のperldoc.jpのシステムで初めて翻訳をする場合、複数箇所を行き来しながら読解する必要があると思う。
そこで、誤字修正など軽微な修正を（ほぼ）自力で行う方法のわかるチュートリアル記事を公開する。

# 目的

- このチュートリアル記事を読むだけで、perldoc.jpの翻訳の軽微修正を作成できる状態になること
- (裏目的: 現状を把握し、今後のPerl Documentワーキンググループの活動のヒントを掴むこと)

# タスク

- [ ] チュートリアルを記載する場所を用意する
  - 案1:  `https://perldoc.jp/tutorial` でチュートリアルを閲覧できるようにし、記事は、`perldoc.jp/tmpl/tutorial.tt`に記載する
    - 関連リポジトリ https://github.com/jpa-perl/perldoc.jp 
  - 案2: ブログなどを用意し、そこに記事を記載する
- [ ] 誤字修正などの軽微な修正を送るチュートリアルを記載する
   - [ ] CVS版 https://perldoc.jp/about
   - [ ] GitHub版 https://github.com/perldoc-jp/module-pod-jp

**Comment by AnaTofuZ** [comment]
るりまの例ですがこういうのがあると良いのでしょうね
https://imaizumimr.hatenablog.com/entry/2020/12/02/235121
となってくるとエントリから一発で編集できるようなボタンがあると最高そう

**Comment by kfly8** [comment]
何はともあれ、現状の仕組みを理解必要だと思うので、それぞれ何かしら翻訳を反映してみますかね。

**Comment by bayashi** [comment]
https://github.com/perldoc-jp/module-pod-jp のコントリビュータに自分がいてびっくりしているところなんですが、ドキュメントはなんか最低限でいいような気がします(という意味ではすでにそろっている？)。
そのうえで、AnaTofuZさんもおっしゃっているような、極端に言うとチュートリアルドキュメントなしでも翻訳作業にはいっていけるような導線づくりみたいなことができるといいですね。
昔、自分がコミットしたようなときに比べるとgithubも進化してるのでgithub上で直接編集というアプローチなんかもありなのかなという気もします(権限問題がありますかね。事前にforkさせる必要がある？)。

まあ、いずれにしろウォーミングアップでひとつなにか翻訳やってみましょうか

**Comment by bayashi** [comment]
完全にアイデアベースですけど、なんらか翻訳してもらうにあたって、現状だと翻訳するファイルを手動でレイアウトするようになってますけど、これ、最初からもう全部ぶっこまれてていいんじゃないかと思ったりした。翻訳が(一部でも)されてるフラグのようなものを別にもって、パブリッシュするか判断するような仕組みにするとして。翻訳開始の負担軽減には事前に自動で全ブッコミでいいんじゃないかというきがしました

**Comment by bayashi** [comment]
もしくは、ヘルパースクリプトが自動レイアウトしてテンプレート生成みたいなことやってくれるとかですかね。

あと、もろもろ翻訳のお作法的なものをCI化とかできるとよさそうだなと思ったりもしました

**Comment by kfly8** [comment]
> https://github.com/perldoc-jp/module-pod-jp のコントリビュータに自分がいてびっくりしているところ

w

**Comment by kfly8** [comment]
まだ未着手なのですが、自分も思いついたらアイデア書き留めていきますー。

**Comment by bayashi** [comment]
既存のチュートリアルをいま読み返してみたんですが、わりと読めばできそうかなという気はしますね。内容が古いのでいくらか更新した方が良い観点はありましたが。
* CSVはいったん忘れていいのでは
* ディレクトリレイアウトは説明の中ではいったん一意に決める感じで良いのでは
* 逆引き風のチュートリアルがわかりやすいのでは


逆引き風について、
以下パターンについて個別に(ページ分けるほどではなくて良いですが)チュートリアルがあるといいのかなと思いました。

1. 翻訳されたページをみて、その修正をする
1. 存在しないページをあらたに翻訳する
    1. CPANモジュールの POD を翻訳する
    1. Perl自体の POD を翻訳する

この方針で良ければ、いったん既存の情報を編集した感じのをgistに書いてみますがいかがでしょう

**Comment by kfly8** [comment]
@bayashi レス遅くなってすいませんでした。
確かに、CVS版のことを一旦、忘れて考えれば、GitHub版一本道でスッキリしそうですね。
(細かいですが、念の為、CSV -> CVS版のことですよね。）
良さそうです！

**Comment by kfly8** [comment]
非効率かもしれないですが、自分はCVS版の方で翻訳をあげてみたいと思います。

**Comment by bayashi** [comment]
@kfly8 CVS歴浅くて間違えてしまいましたｗｗ

一発あれこれコメントつける用のたたき台をあげてみますね！

**Comment by bayashi** [comment]
ざっと以下のような感じになりますかね。ばっさり情報をそぎ落としています。[ここのREADME](https://github.com/perldoc-jp/module-pod-jp) を置き換えるイメージでいます。

<hr>

# Perl の英語ドキュメントを翻訳して公開する方法

CPAN モジュールの POD や Perl 本体の英語ドキュメントを日本語に翻訳して perldoc.jp で公開する方法です。

## 公開場所

[http://perldoc.jp/](http://perldoc.jp/)

## 翻訳して貢献する手順

すでに存在する翻訳ドキュメントを修正する場合も、新しい翻訳ドキュメントを追加する場合も、基本的に手順は同じです。[この Github Repository 自体](https://github.com/perldoc-jp/module-pod-jp) を fork して PR を送ってください。

[翻訳作業自体の作法はこちらに詳細なドキュメント](http://perldoc.jp/manners)があります。

[過去の PR](https://github.com/perldoc-jp/module-pod-jp/pulls?q=is%3Apr+is%3Aclosed) を参考にすると良いかもしれません。

## FAQ

### 翻訳について、オリジナルの著者への報告は必要ですか？

ほとんどの CPAN モジュールが改変と再配布が許可されているライセンスなので、元々のドキュメントの著者に翻訳の報告をする必要はありません。ライセンスが不明な場合や、改変と再配布が許可されていないライセンスの場合には、著者に連絡を取ってください。

### JPRPとは何ですか？

Perl ドキュメントの翻訳関連でしばしば目にする JPRP は、[Japanized Perl Resources Project (JPRP)](https://perldocjp.osdn.jp/)のことです。

### 質問はどこでできますか？

気軽に [issue を立てましょう](https://github.com/jpa-perl/wg-perl-document/issues/new)！

### コミット権限はもらえますか？

PR を送るとしれっと追加してもらえるようです！

**Comment by kfly8** [comment]
@bayashi 最高です！

**Comment by kfly8** [comment]
試しに、PRを作ってみました！

https://github.com/perldoc-jp/module-pod-jp/pull/8

**Comment by argrath** [comment]
* READMEを置き換えると言うことであれば、冒頭に「そもそもこのリポジトリはなにものか」について軽く説明がほしい気がします。
 * 「perldoc.jpにあるけれどもこのリポジトリにない文書を修正するにはJPRP側を修正する必要がある」ということも軽く触れるとよいかもです。

**Comment by bayashi** [comment]
@argrath こんな感じでいかがでしょう？
<hr>

# このリポジトリについて

<https://github.com/perldoc-jp/module-pod-jp>

日本語に翻訳された CPAN モジュールの POD や Perl 本体のドキュメントが置かれています。

誰でも PR を作成して貢献することができます。

## 公開場所

[http://perldoc.jp/](http://perldoc.jp/)

## 翻訳して貢献する手順

すでに翻訳が存在するかどうかは [http://perldoc.jp/](http://perldoc.jp/) で検索してください。

ドキュメントの修正や追加は、[この module-pod-jp](https://github.com/perldoc-jp/module-pod-jp) を fork して PR を送ってください。

[翻訳作業自体の作法はこちらに詳細なドキュメント](http://perldoc.jp/manners)があります。

[過去の PR](https://github.com/perldoc-jp/module-pod-jp/pulls?q=is%3Apr+is%3Aclosed) を参考にすると良いかもしれません。

### 別の翻訳リソースも存在します

このリポジトリ [module-pod-jp](https://github.com/perldoc-jp/module-pod-jp) の前身にあたる、[Japanized Perl Resources Project (JPRP)](https://perldocjp.osdn.jp/) が存在します。

[http://perldoc.jp/](http://perldoc.jp/) は両方の翻訳ドキュメントがマージして公開されています。

[http://perldoc.jp/](http://perldoc.jp/) に翻訳が存在するのに、この [module-pod-jp](https://github.com/perldoc-jp/module-pod-jp) リポジトリにソースが見つからない場合、[Japanized Perl Resources Project (JPRP)](https://perldocjp.osdn.jp/) の CVS リポジトリも参照してください。

## FAQ

### 翻訳について、オリジナルの著者への報告は必要ですか？

ほとんどの CPAN モジュールが改変と再配布が許可されているライセンスなので、元々のドキュメントの著者に翻訳の報告をする必要はありません。ライセンスが不明な場合や、改変と再配布が許可されていないライセンスの場合には、著者に連絡を取ってください。

### 質問はどこでできますか？

気軽に [issue を立てましょう](https://github.com/jpa-perl/wg-perl-document/issues/new)！

### コミット権限はもらえますか？

PR を送るとしれっと追加してもらえるようです！

**Comment by bayashi** [comment]
よさそうならPRにしてみます

**Comment by argrath** [comment]
良くなったと思います!

**Comment by bayashi** [comment]
#perldocjp@freenodeって生きてるんでしょうか
これに代わる場所ってあるんでしょうか

**Comment by argrath** [comment]
私の知る限り何年も流量なかったので、消滅したと考えてよいと思います。
代わりもない気がします…。

**Comment by bayashi** [comment]
なるほどですね。。

**Comment by kfly8** [comment]
module-pod-jpのREADMEを更新した。
https://github.com/perldoc-jp/module-pod-jp/pull/9
