### ISSUE TITLE
2023-02 Perlのモジュールの翻訳

### ISSUE THREAD

**Issue by kfly8** [perldoc-jp/wg-perl-document#17]
## 背景、取り組みの理由

- [アンケートの結果、最近のPerl事情を掴みたいニーズ](https://blog.perlassociation.org/entry/2022/12/23/180000)があるよう
- そういった理由で、https://github.com/jpa-perl/wg-perl-document/issues/7 RFCの翻訳の活動もしている
- ただ、RFCの内容によっては、翻訳者にPerl力が必要でハードルが高いところがあった
- 最近のPerl事情を掴みつつ、翻訳のネタとして、Perlのモジュールの翻訳を検討するのはどうかと考えた
- そして、ワーキンググループで取り組むなら、どのモジュールを翻訳するかテーマ設定し、定期的に進捗を追うことで、アウトプットが安定するのではないかと思った

## 何をするか

次の候補になりそうなものから、翻訳者は訳したいモジュールを選び、このissueにコメントをする。

- [コアモジュール](https://perldoc.perl.org/modules)を翻訳する
- [metacpanのリーダーボード](https://metacpan.org/favorite/leaderboard)に掲載されているモジュールを翻訳する
- [Perl Hackers Hub](https://gihyo.jp/list/group/Perl-Hackers-Hub) で紹介されたモジュールを翻訳する
- [Awesome Perl](https://github.com/hachiojipm/awesome-perl) で紹介されたモジュールを翻訳する

## 推奨行動

- 進捗を出したらコメントをする
- そのコメントにいいね、エライといったリアクションをする

**Comment by kfly8** [comment]
何を翻訳するか迷うなー

- Type::Tiny ? https://metacpan.org/pod/Type%3A%3ATiny
  - 量多そうだけど、便利だと思うのよね。
- App::cpm ? https://metacpan.org/dist/App-cpm
- builtin ? https://perldoc.perl.org/builtin
  - 最近、これのrfc訳したし。
- Data::Printer
  - よく使うけれど、翻訳記事がなかった
- Test2
  - 量多そうだけど、便利だと思うのよね。
- Mojolicious
  - あんまり使ったことないけれど、リーダーボードみると無視できない


他のワーキンググループの人の意見を聞きつつ私は決めようかな。

**Comment by bayashi** [comment]
App::cpmはtutrialとか翻訳あるといいかなと思ったりしたんですが、日本語のドキュメント的な記事もそこそこ検索すれば見つかるので、あえて翻訳することもないかなという気がする。
(どっちかというと、cpmあたりは実装解説みたいなのがみたいような)

基本的にはgoogleで検索しても使い方とか書いてるのがない(少ない)けど、重要なモジュール、みたいなやつからやってくかんじですかね

Test2あたりがよさそうかなと思ったんですけど、現状確認から必要ですね。そしておっしゃる通り分量ががが

**Comment by kfly8** [comment]
確かに、日本語のコンテンツは多いかもしれないですね！（実装解説読みたい）

> 基本的にはgoogleで検索しても使い方とか書いてるのがない(少ない)けど、重要なモジュール、みたいなやつからやってくかんじですかね

良さそうです！

Test2良さそうです！
Test2に関しては、Manualがあるので、それでいくらか絞れるかなと思いました・・！
（それでも20近くありますがが）

**Comment by kfly8** [comment]
:memo: 理事会にて

- Mooとかもありかも。
  - Mouse,Mooseわかっていればわかるでしょってニュアンスで触れられないがち
  - ← perlにclass 構文が入るから、そっちの方が訳すべき可能性あるかも？
- Data::Dumper, Data::Printerあたり
  - Perl入学式でよく使うけれど、訳されていないもの
- JSON::PP
  - Perl入学式でよく使うけれど、訳されていないもの（Web::Hookで使ってる）

**Comment by bayashi** [comment]
> perlにclass 構文が入る

これの英語ドキュメントってあるんでしょうか。RFCにあるのかな

**Comment by kfly8** [comment]
perlのclassは、RFCはないんですよね。

- このPRが、feature classの実装の本体ですね。　https://github.com/Perl/perl5/pull/20647
- perldocは、この辺り
  - [perlclass](https://github.com/leonerd/perl5/blob/734489d7165432397bd6e8d550b15ef7767a9224/pod/perlclass.pod)
  - [perlclassguts](https://github.com/leonerd/perl5/blob/734489d7165432397bd6e8d550b15ef7767a9224/pod/perlclassguts.pod)
  - 【追記】[perlclasstut](https://gist.github.com/Ovid/e0381355da7136654e92418a43c97611)

**Comment by kfly8** [comment]
先駆けて記事書いていくのはいいかもですね！
> class

**Comment by bayashi** [comment]
すげーついにPerl 5本体に！
これは日本語記事あまりないなら翻訳しますか

**Comment by bayashi** [comment]
ぱっと検索した感じ、この最新のはなかなか見つからないですね
古のはいっぱいでてきますが

**Comment by ybrliiu** [comment]
あると良さそうなもの考えてみました

- List::Util
  - 既に翻訳済みですが, バージョンアップで関数が結構増えているので差分が翻訳されると嬉しそうです
- Teng
  - 最近でもよく使われているORMのドキュメントも1つくらいあると良さそう
- Path::Tiny
  - パス操作, ファイル操作系のユーティリティモジュールも使う機会が多いと思うのであると良さそうです

**Comment by kfly8** [comment]
List::Util関数増えてますよね！builtinに入ってくる関数もありそう。

Tengも確かに。Tengと聞いて思い出したのですが、SQL::Makerなんかは、Anikiも利用してて、特に古巣からのニーズがありそう？

Path::Tiny確かに！

**Comment by kfly8** [comment]
classに関して、RFCがなかったというのは不正確でした・・！
perl/RFCsにはないけれど、RFCはこちらにありました。https://github.com/Ovid/Cor

classに関しては、このp5のやりとりを見るといろんなところで話しすぎたと話してますねw
https://www.nntp.perl.org/group/perl.perl5.porters/2022/12/msg265177.html

そしてこのやりとりをみていて、classのチュートリアルを見つけました！こちらも訳せると良さそうですね。（perl5本体に入ったら）
https://gist.github.com/Ovid/e0381355da7136654e92418a43c97611

**Comment by kfly8** [comment]
classに関して、このイベントで情報もう少し追いやすくなりそうですね。
https://boston-pm.github.io/#schedule

perl本体に入ってから訳すことを考えるより、利用を視野にいれて考えると、
https://metacpan.org/pod/Feature::Compat::Class
こちらを訳す方が良いかも？（feature classが使えるならそれを使い、使えなければ、Object::Padにfallbackするモジュール）

**Comment by kfly8** [comment]
某社で聞くと、PSGI/Plack, SQL::QueryMaker, Test2 方面, List 方面（List::Util, List::MoreUtil, List::UtilsBy）という声がありました！

**Comment by bayashi** [comment]
[Feature::Compat::Class](https://metacpan.org/pod/Feature::Compat::Class) はやれそうですけど、Object::Padは長大で厳しそうですねえ（私にとって
いずれにしろ、タイミング的にPerl 5 本体に入るときでいいかも？正式なドキュメントも用意されるでしょうし、現状のものは OOP他言語で経験があれば、本文が読めなくてもコードからつかめる部分が多いと思うので。

**Comment by kfly8** [comment]
> OOP他言語で経験があれば、本文が読めなくてもコードからつかめる部分が多いと思うので。

確かに！

Object::PadもCorも、ドキュメントが長大ですね・・（私にとっても厳しい。

**Comment by bayashi** [comment]
[Feature::Compat::Class](https://metacpan.org/pod/Feature::Compat::Class) の翻訳をはじめました

**Comment by kfly8** [comment]
このissueでの議論を踏まえ、3つに絞ってissueを切りました！
好きなissueを拾ってもらえると良いのかなと！

- https://github.com/jpa-perl/wg-perl-document/issues/21
- https://github.com/jpa-perl/wg-perl-document/issues/20
- https://github.com/jpa-perl/wg-perl-document/issues/19

このissueの役目は、一旦終えたと思うので、closeします。
また、次に、何を翻訳したら良さそうか議論する場合は、discussion機能を使おうと思います。
discussionを開いてみました。
- https://github.com/jpa-perl/wg-perl-document/discussions/22

## 補足

この議論で挙がったモジュールを全て、issueに切らなかったのは、集中すべき的を絞りたかったからです。
そして、issueを管理しやすくしたかったからです（たくさんのことを同時並行すると、私はしんどい）

この3つに入らなかったからといって、翻訳するつもりがないわけではありません。
この3つ以外のモジュールを翻訳するのは、個人の自由！と思っています。
